# Tomcat
server:
  # 端 口
  port: 9211
  # Servlet
  servlet:
    # Session
    session:
      # 超 时 时 间
      timeout: 12000m

# Spring 配置 设置0 或者小于0 为永不过期
spring:
  session:
    timeout: 12000m

  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
# 日志配置
#logging:
#  config: classpath:logback-spring.xml
